# Generated by Django 6.0.3 on 2026-03-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='duracao',
        ),
    ]
